general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  startup_commands: ['shell-exec %userprofile%/.glzr/zebar/start.bat']

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: true

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

gaps:
  # Gap between adjacent windows.
  inner_gap: '20px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '60px'
    right: '20px'
    bottom: '20px'
    left: '20px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#ff6961ee'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: true

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
    display_name: 'school'
    keep_alive: true
    bind_to_monitor: 0
  - name: '2'
    display_name: 'more school'
    keep_alive: true
    bind_to_monitor: 0
  - name: '3'
    display_name: 'other'
    keep_alive: true
    bind_to_monitor: 0
  - name: '4'
    display_name: 'other other'
    keep_alive: true
    bind_to_monitor: 0
  - name: '5'
    display_name: 'games'
    keep_alive: true
    bind_to_monitor: 0
  - name: '6'
    display_name: 'school'
    keep_alive: true
    bind_to_monitor: 1
  - name: '7'
    display_name: 'other'
    keep_alive: true
    bind_to_monitor: 1
  - name: '8'
    display_name: 'more'
    keep_alive: true
    bind_to_monitor: 1
  - name: '9'
    display_name: 'side'
    keep_alive: true
    bind_to_monitor: 2
  - name: '0'
    display_name: 'side two'
    keep_alive: true
    bind_to_monitor: 2

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys.PowerAccent' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper*' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

  # When enabled, all keybindings are disabled except for ctrl+alt+f12+shift+p which
  # returns to default keybindings.
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['ctrl+alt+f12+shift+p']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['ctrl+alt+f12+h']
  - commands: ['focus --direction right']
    bindings: ['ctrl+alt+f12+l']
  - commands: ['focus --direction up']
    bindings: ['ctrl+alt+f12+k']
  - commands: ['focus --direction down']
    bindings: ['ctrl+alt+f12+j']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['ctrl+alt+f12+shift+h', 'ctrl+alt+f12+shift+left']
  - commands: ['move --direction right']
    bindings: ['ctrl+alt+f12+shift+l', 'ctrl+alt+f12+shift+right']
  - commands: ['move --direction up']
    bindings: ['ctrl+alt+f12+shift+k']
  - commands: ['move --direction down']
    bindings: ['ctrl+alt+f12+shift+j']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['ctrl+alt+f12+u']
  - commands: ['resize --width +2%']
    bindings: ['ctrl+alt+f12+p']
  - commands: ['resize --height +2%']
    bindings: ['ctrl+alt+f12+o']
  - commands: ['resize --height -2%']
    bindings: ['ctrl+alt+f12+i']

  # As an ctrl+alt+f12ernative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['ctrl+alt+f12+r']

  # Disables all keybindings until ctrl+alt+f12+shift+p is pressed again.
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['ctrl+alt+f12+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['ctrl+alt+f12+v']

  # Change focus from tiling windows -> floating -> fullscreen.
  # - commands: ['wm-cycle-focus']
  #   bindings: ['ctrl+alt+f12+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['ctrl+alt+f12+shift+space']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['ctrl+alt+f12+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['ctrl+alt+f12+f']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['ctrl+alt+f12+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['ctrl+alt+f12+shift+q']
 
  # Kill GlazeWM process safely.
  - commands: ['wm-exit', 'shell-exec TASKKILL /F /IM zebar.exe /T']
    bindings: ['ctrl+alt+f12+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config', 'shell-exec taskkill /IM "zebar.exe" /F', "shell-exec %userprofile%/.glzr/zebar/start.bat",]
    bindings: ['ctrl+alt+f12+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['ctrl+alt+f12+shift+w']

  # Launch CMD terminal. ctrl+alt+f12ernatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec wt']
    bindings: ['ctrl+alt+f12+enter']

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ['focus --next-workspace']
    bindings: ['ctrl+alt+f12+s']
  - commands: ['focus --prev-workspace']
    bindings: ['ctrl+alt+f12+a']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['ctrl+alt+f12+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['ctrl+alt+f12+1']
  - commands: ['focus --workspace 2']
    bindings: ['ctrl+alt+f12+2']
  - commands: ['focus --workspace 3']
    bindings: ['ctrl+alt+f12+3']
  - commands: ['focus --workspace 4']
    bindings: ['ctrl+alt+f12+4']
  - commands: ['focus --workspace 5']
    bindings: ['ctrl+alt+f12+5']
  - commands: ['focus --workspace 6']
    bindings: ['ctrl+alt+f12+6']
  - commands: ['focus --workspace 7']
    bindings: ['ctrl+alt+f12+7']
  - commands: ['focus --workspace 8']
    bindings: ['ctrl+alt+f12+8']
  - commands: ['focus --workspace 9']
    bindings: ['ctrl+alt+f12+9']
  - commands: ['focus --workspace 0']
    bindings: ['ctrl+alt+f12+0']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['ctrl+alt+f12+shift+a']
  - commands: ['move-workspace --direction right']
    bindings: ['ctrl+alt+f12+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['ctrl+alt+f12+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['ctrl+alt+f12+shift+s']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['ctrl+alt+f12+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['ctrl+alt+f12+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['ctrl+alt+f12+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['ctrl+alt+f12+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['ctrl+alt+f12+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['ctrl+alt+f12+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['ctrl+alt+f12+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['ctrl+alt+f12+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['ctrl+alt+f12+shift+9']
  - commands: ['move --workspace 0', 'focus --workspace 0']
    bindings: ['ctrl+alt+f12+shift+0']

  # - commands: ["focus --next-workspace"]
    # bindings: ["ctrl+alt+f12+oem_period"]
  # - commands: ["focus --prev-workspace"]
    # bindings: ["ctrl+alt+f12+oem_comma"]

  # - commands: ["focus --next-workspace"]
  #   bindings: ["ctrl+alt+f12+oem_period"]
  # - commands: ["focus --prev-workspace"]
  #   bindings: ["ctrl+alt+f12+oem_comma"]

  - commands: ["shell-exec warp-cli connect"]
    bindings: ["ctrl+alt+f12+shift+v"]
  - commands: ["shell-exec nircmd monitor off"]
    bindings: ["ctrl+alt+f12+oem_comma"]
  - commands: ["shell-exec nircmd monitor on"]
    bindings: ["ctrl+alt+f12+oem_period"]
